# Change this to your env.
name: gomezmh

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: master

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: master