name: qa-midrc-helm

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: chore/improve-gen3-workflow

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: chore/improve_gen3workflow