name: qa-midrc-helm

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: feat/additional-crossplane

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: feat/crossplane-test