apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}-additional-configs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops-dev.git'
      targetRevision: {{ .Values.gitopsBranch }}
      path: qaplanetv1/qa-environments/{{ .Values.name }}/additional-configs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.name }}
  ignoreDifferences:
    - 
      kind: "Secret"
      jsonPointers:
      - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
