name: qa-mc2dp-helm

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: master

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: feat/qa-mc2dp-crossplane-and-other-values-yaml-updates
