# Change this to your env. 
name: qa-heal-helm

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: chore/handle-stata-license-secret

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: chore/update-stata-license-secret
