# Change this to your env. 
# !!! Needs to match the folder name. 
# F.ex qa-brh
name: jian

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: feat/dcf-validation

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: master