# Change this to your env.
# !!! Needs to match the folder name.
# F.ex qa-brh
name: qa-mickey-helm

# What branch of helm
helmBranch: feat/additional-crossplane

# What branch of gitops
gitopsBranch: master
